language: python

cache:
  - apt
  - pip
python:
  # - 2.7
  - 3.6
  # - pypy2.7-5.8.0
  # - pypy3.5-5.8.0
env:
    - ZMQ=
    - ZMQ=bundled
before_install:
  - |
    if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update
      export HOMEBREW_NO_AUTO_UPDATE=1
      export TEST_ENV="$PWD/test-env-$PYTHON"
      export PATH=$TEST_ENV/bin:$PATH
      rm -rf $TEST_ENV
    fi
  - bash ci/before-install.sh
install:
  - python setup.py build_ext --inplace --zmq=$ZMQ

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PYTHON=python3
        - ZMQ=
    - os: osx
      language: generic
      env:
        - PYTHON=python3
        - ZMQ=bundled
    - os: osx
      language: generic
      env:
        - PYTHON=pypy3
        - ZMQ=bundled
        - LDFLAGS="-undefined dynamic_lookup"
    - os: osx
      language: generic
      env:
        - PYTHON=pypy
        - ZMQ=bundled
    - os: osx
      language: generic
      env:
        - PYTHON=python
        - ZMQ=
    # - python: pypy
    #   env: ZMQ=bundled
    # - python: 3.6-dev
    #   env: ZMQ=bundled
    # - python: 3.6
    #   env:
    #     - ZMQ=
    #     - NOTORNADO=1
    # - python: 3.5
    #   env: ZMQ=libzmq
    # - python: 3.4
    #   env: ZMQ=zeromq4-x
    # - python: 3.4
    #   env: ZMQ=zeromq4-1
    # - python: 3.4
    #   env: ZMQ=zeromq3-x
    # - python: 3.3
    #   env: ZMQ=
    # - python: nightly
    #   env: ZMQ=
    # - python: nightly
    #   env: ZMQ=bundled
  allow_failures:
    - env: ZMQ=libzmq
    - python: nightly

script: travis_retry python setup.py test
