language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
env:
    - ZMQ=
    - ZMQ=bundled
    - ZMQ=2.1.11
    - ZMQ=master
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo add-apt-repository -y ppa:pypy/ppa || true; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo apt-get -y update && sudo apt-get -y install pypy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then virtualenv -p /usr/bin/pypy pypy && source pypy/bin/activate; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install -q --use-mirrors py cffi; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -q --use-mirrors cython; fi

  - if [[ -z "$ZMQ" ]]; then sudo apt-get install -qq libzmq3-dev; fi

  - if [[ $ZMQ == '2.1.11' ]]; then wget http://download.zeromq.org/zeromq-2.1.11.tar.gz; tar -xzf zeromq-$ZMQ.tar.gz; fi
  - if [[ $ZMQ == '2.1.11' ]]; then sh -c "cd zeromq-$ZMQ; ./configure; make -j; sudo make install; sudo ldconfig"; fi
  - if [[ $ZMQ == 'master' ]]; then git clone --depth 1 https://github.com/zeromq/libzmq; fi
  - if [[ $ZMQ == 'master' ]]; then sh -c 'cd libzmq; sh autogen.sh; ./configure; make -j; sudo make install; sudo ldconfig'; fi
  - pip install -q --use-mirrors nose

install:
  - if [[ ! -z "$ZMQ" && $ZMQ != 'bundled' ]]; then export ZMQ=/usr/local; fi
  - python setup.py build_ext --inplace --zmq=$ZMQ

matrix:
  exclude:
    - python: pypy
      env: ZMQ=bundled
    - python: 2.6
      env: ZMQ=bundled
    - python: 3.2
      env: ZMQ=bundled
    - python: 2.6
      env: ZMQ=master
    - python: 3.2
      env: ZMQ=master
    - python: 2.6
      env: ZMQ=2.1.11
    - python: 3.2
      env: ZMQ=2.1.11
  allow_failures:
    - env: ZMQ=master

script: python setup.py test
